language: php

matrix:
    include:
        - php: 5.6
    fast_finish: true

sudo: false

before_install:
  - phpenv config-add travis.php.ini
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

script:
  - phpunit --coverage-clover=coverage.clover

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    email:
        recipients:
            - guillaume.morel@gmx.com
        on_success: change
        on_failure: change

